# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "240c7647721a1e82013676ff6cd0c791"
application_url = "https://silver-yodel-jj7vvg9grr6qcq4xj-4040.app.github.dev"
embedded = true
name = "Try-On AI"
handle = "try-on-ai-1"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://silver-yodel-jj7vvg9grr6qcq4xj-4040.app.github.dev/auth/callback",
  "https://silver-yodel-jj7vvg9grr6qcq4xj-4040.app.github.dev/auth/shopify/callback",
  "https://silver-yodel-jj7vvg9grr6qcq4xj-4040.app.github.dev/api/auth/callback"
]

[pos]
embedded = false
